# Generated by Django 5.0.7 on 2024-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
