# Generated by Django 5.0.7 on 2024-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_pressuresensor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
