# Generated by Django 5.0.7 on 2024-07-23 20:07

import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_pressuresensor_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresensor',
            name='serial_number',
            field=models.CharField(default=sensors.models.generate_serial_number, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
