# Generated by Django 5.0.7 on 2024-07-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_tags', '0001_initial'),
        ('sensors', '0004_alter_pressuresensor_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressurereading',
            name='tags',
            field=models.ManyToManyField(blank=True, to='my_tags.tag'),
        ),
        migrations.AddField(
            model_name='pressuresensor',
            name='tags',
            field=models.ManyToManyField(blank=True, to='my_tags.tag'),
        ),
    ]
